package ClassesInterface;

import Classes.*;
import Exceptions.PecaNaoExisteException;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;

/**
 * Classe associada à adição de extras ao carro durante a compra por parte do cliente
 */
public class Extras extends javax.swing.JFrame {
    /** Variáveis de instância que contêm informação sobre o sistema */
    private ConfiguraFacil cf;
    private Cliente cliente;
    private Modelo modelo;
    private Pacote pacote;
    /**
     * Construtor vazio
     */
    public Extras() {
        initComponents();
    }
    /**
     * Construtor parametrizado
     * 
     * @param cf Classe que contém informação sobre o sistema
     * 
     * @param c Variável que contém informação sobre o cliente
     * 
     * @param m Variável que contém informação sobre o modelo
     * 
     * @param p Variável que contém informação sobre o pacote
     */
    public Extras(ConfiguraFacil cf, Cliente c, Modelo m, Pacote p){
        this();
        this.cf = cf;
        this.cliente = c;
        this.modelo = m;
        this.pacote = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spoiler = new javax.swing.JRadioButton();
        automatico = new javax.swing.JRadioButton();
        escape = new javax.swing.JRadioButton();
        Confirmar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        teto = new javax.swing.JRadioButton();
        vidrosEscuros = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        climatizacao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        spoiler.setText("Spoiler");

        automatico.setText("Condutor Automatico");

        escape.setText("Escape Regulavel");

        Confirmar.setText("Confirmar");
        Confirmar.setToolTipText("Confirmar compra");
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.setToolTipText("Voltar atrás");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        teto.setText("Teto de Abrir");
        teto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tetoActionPerformed(evt);
            }
        });

        vidrosEscuros.setText("Vidros Escurecidos");

        jLabel2.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        jLabel2.setText(" Extras");

        climatizacao.setText("Sistema de Climatização");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(escape)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(climatizacao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spoiler)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(automatico)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vidrosEscuros)
                            .addComponent(teto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Voltar)
                        .addGap(14, 14, 14)
                        .addComponent(Confirmar)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teto)
                    .addComponent(escape)
                    .addComponent(climatizacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spoiler)
                    .addComponent(automatico)
                    .addComponent(vidrosEscuros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voltar)
                    .addComponent(Confirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que permite escolher peças extra para o carro por parte do cliente
     * 
     * @return extras escolhidos para o carro
     */
    public List<String> extrasEscolhidos(){
        List <String> pecas = new ArrayList<>();
        if (this.escape.isSelected())
            pecas.add(this.escape.getText());
        if (this.climatizacao.isSelected())
            pecas.add(this.climatizacao.getText());
        if (this.teto.isSelected())
            pecas.add(this.teto.getText());
        if (this.spoiler.isSelected())
            pecas.add(this.spoiler.getText());
        if (this.automatico.isSelected())
            pecas.add(this.automatico.getText());
        if (this.vidrosEscuros.isSelected())
            pecas.add(this.vidrosEscuros.getText());
        return pecas;
    }
    /**
     * Método que confirma uma ação correspondente ao botão "Confirmar" 
     * 
     * @param evt evento associado ao botão "Confirmar"
     */
    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        List<Peca> list = this.cf.stringToPeca(extrasEscolhidos());
        List<Peca> pac = this.cf.stringToPeca(this.pacote.getPecas());
        pac.addAll(list);
        if(this.cf.validaPecas(pac)){
            ConfirmaCompra cc = new ConfirmaCompra(this.cf, this.cliente, this.modelo, this.pacote, list);
            cc.setVisible(true);
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Peças Inválidas", "Peças Inválidas", 0);
        }
    }//GEN-LAST:event_ConfirmarActionPerformed
    /**
     * Método que permite ao utilizador voltar ao menu principal a partir do menu "Extras"
     * 
     * @param evt evento associado ao botão "Voltar"
     */
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void tetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Extras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar;
    private javax.swing.JButton Voltar;
    private javax.swing.JRadioButton automatico;
    private javax.swing.JRadioButton climatizacao;
    private javax.swing.JRadioButton escape;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton spoiler;
    private javax.swing.JRadioButton teto;
    private javax.swing.JRadioButton vidrosEscuros;
    // End of variables declaration//GEN-END:variables
}
